export const ENGINE_DEFAULTS = {
  checksDir: "./.checkr/checks",
  fixesDir: "./.checkr/fixes",
  include: ["**/*.{js,jsx,ts,tsx}"],
  exclude: [],
  gitignore: null,
  scanPath: ".",
  scanMode: "full",
  bail: true,
  parallel: true,
  concurrency: 4,
  ignoreMarker: "@checkr-ignore",
  reporter: "default",
  reportFile: null,
  verbose: false,
  cache: true,
  cacheDir: ".checkr-cache",
  steps: undefined,
  skip: [],
  only: [],
  stepOrder: undefined,
  disable: [],
  enable: [],
  cwd: process.cwd(),
};
