export const ENGINE_DEFAULTS = {
  checksDir: "./.chekr/checks",
  fixesDir: "./.chekr/fixes",
  include: ["**/*.{js,jsx,ts,tsx}"],
  exclude: [],
  gitignore: null,
  scanPath: ".",
  scanMode: "full",
  bail: true,
  parallel: true,
  concurrency: 4,
  ignoreMarker: "@chekr-ignore",
  reporter: "default",
  reportFile: null,
  verbose: false,
  cache: true,
  cacheDir: ".chekr-cache",
  marketplace: {
    repository: "owner/chekr-marketplace",
    branch: "main",
  },
  steps: undefined,
  skip: [],
  only: [],
  stepOrder: undefined,
  disable: [],
  enable: [],
  cwd: process.cwd(),
  experimental: {
    codeGraph: {
      enabled: false,
      engine: "auto",
      persistDir: ".chekr-graph",
      indexOn: ["imports", "exports", "symbols"],
      autoIndex: false,
      maxDepth: 5,
      suggestIndexing: true,
      bigRepoThreshold: 500,
    },
  },
};
